name = "Colony Protocol: Liminal"
author = "MichaelHeaton"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27e868cf586fdb9d1800566393d250673703f4be4930be2ca252b5b7da78a907"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
acceptable-game-versions = ["1.21"]
