name = "Colony Protocol: Liminal"
author = "MichaelHeaton"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04d173a298c13691f8aeeb3e407b7808701bb4f646cc01490c3265e51a9a2917"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
acceptable-game-versions = ["1.21"]
