name = "Colony Protocol: Liminal"
author = "MichaelHeaton"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6935be914b091705b2d73ffd7f410bee268d4a7847203e65ff8dd627ba501d5b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
acceptable-game-versions = ["1.21"]
