#!/usr/bin/env bash
# One command: recipe + item dump from the installed mod JARs, on a new branch, committed, pushed, PR opened.
#   make recipe-pr
# Needs: python3, git, a pulled Prism instance (CP-<Pack>-Dev) or RECIPE_WIKI_MODS_DIR, and gh (optional;
# without gh the script prints the PR link instead).
set -euo pipefail

ROOT=$(git rev-parse --show-toplevel)
cd "$ROOT"
PACK=$(basename "$ROOT" | sed 's/.*cp-//')
STAMP=$(date +%Y%m%d-%H%M)
BRANCH="chore/recipe-dump-$PACK-$STAMP"
BASE=${BASE_BRANCH:-main}

say() { printf '\n==> %s\n' "$*"; }
die() { printf '\nSTOP: %s\n' "$*" >&2; exit 1; }

[ -z "$(git status --porcelain --untracked-files=no)" ] || die "tracked files have uncommitted changes. Commit or stash them first (git status)."
UNTRACKED=$(git status --porcelain --untracked-files=normal | grep '^??' || true)
[ -z "$UNTRACKED" ] || { echo "Note: ignoring untracked files (they stay as they are):"; echo "$UNTRACKED" | head -10; }
command -v python3 >/dev/null || die "python3 not found"

START_REF=$(git rev-parse --abbrev-ref HEAD)
say "Updating $BASE and creating $BRANCH"
git fetch origin "$BASE"
git checkout -b "$BRANCH" "origin/$BASE"
COMMITTED=""
# If anything fails before the commit, put the checkout back where it was (only generated files can differ).
undo() {
  rc=$?
  if [ "$rc" -ne 0 ] && [ -z "$COMMITTED" ]; then
    echo; echo "Failed before committing: returning to $START_REF and removing $BRANCH"
    git checkout -q -f "$START_REF" && git branch -D "$BRANCH" >/dev/null 2>&1 || true
  fi
}
trap undo EXIT

say "Dumping recipes and items from the installed mod JARs (can take a few minutes)"
make recipe-audit

say "Staging generated data"
git add docs/recipe_data.json docs/recipe-analyze
# Some packs track the browseable HTML too (Liminal ignores it)
if git ls-files --error-unmatch docs/recipe_wiki.html >/dev/null 2>&1; then git add docs/recipe_wiki.html; fi
if git diff --cached --quiet; then
  echo "No change in the dump compared to $BASE. Nothing to commit."
  git checkout -q "$START_REF"
  git branch -D "$BRANCH" >/dev/null
  exit 0
fi

PACK_CAP=$(python3 -c "import sys; print(sys.argv[1].capitalize())" "$PACK")
MODS_DIR=${RECIPE_WIKI_MODS_DIR:-$HOME/Library/Application Support/PrismLauncher/instances/CP-$PACK_CAP-Dev/minecraft/mods}
JARS=$(find "$MODS_DIR" -maxdepth 1 -name '*.jar' 2>/dev/null | wc -l | tr -d ' ')
ITEMS=$(python3 - <<'PY'
import json
d = json.load(open("docs/recipe_data.json"))
print(d.get("item_count", len(d.get("recipes", d))))
PY
)
COMMITTED=1
git commit -q -m "chore($PACK): refresh recipe and item dump from installed mods

$JARS mod jars scanned; $ITEMS recipe entries in docs/recipe_data.json.
Generated by make recipe-pr."

say "Pushing $BRANCH"
git push -u origin "$BRANCH"

BODY="Generated by \`make recipe-pr\` from the installed $PACK mod JARs ($JARS scanned).

- \`docs/recipe_data.json\`: item id to recipes ($ITEMS entries)
- \`docs/recipe-analyze/\`: per-mod item lists and counts

Docs only. No pack files changed."

if command -v gh >/dev/null && gh auth status >/dev/null 2>&1; then
  say "Opening pull request"
  gh pr create --draft --base "$BASE" --head "$BRANCH" \
    --title "chore($PACK): refresh recipe and item dump" --body "$BODY"
else
  REPO=$(git remote get-url origin | sed -E 's#(git@github.com:|https://github.com/)##; s#\.git$##')
  say "gh is not set up. Open the PR here:"
  echo "https://github.com/$REPO/compare/$BASE...$BRANCH?expand=1"
fi
say "Done."
