[creativeModeTabs]
	enableCreativeModeTabs = false
	syncSelectedCreativeModeTab = true
	showCreativeTabNameInSearchbar = false
	disabledCreativeModeTabs = ["minecraft:op_blocks"]

[stackGroups]
	enableStackGroups = true
	enableCreateStackGroupButton = true

[miscellaneous]
	emiOnlyInRecipeBook = false
